[workspace]
members = ["pyqir", "qirlib"]
resolver = "2"

[workspace.package]
authors = ["Microsoft"]
version = "0.11.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/qir-alliance/pyqir"
repository = "https://github.com/qir-alliance/pyqir"

