[workspace]
members = ["iqm_pyqir", "qirlib"]
resolver = "2"

[workspace.package]
authors = ["Microsoft"]
version = "0.10.6"
edition = "2021"
license = "MIT"
homepage = "https://github.com/qir-alliance/iqm_pyqir"
repository = "https://github.com/qir-alliance/iqm_pyqir"

